package protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SSMessage.proto

public final class SSMessage {
  private SSMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>CLIENT_STATE_CHANGED = 1;</code>
     */
    CLIENT_STATE_CHANGED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>CLIENT_STATE_CHANGED = 1;</code>
     */
    public static final int CLIENT_STATE_CHANGED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return CLIENT_STATE_CHANGED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SSMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Type)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.Type type = 1;</code>
     */
    Type getType();

    /**
     * <code>bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>string content2 = 3;</code>
     */
    String getContent2();
    /**
     * <code>string content2 = 3;</code>
     */
    com.google.protobuf.ByteString
        getContent2Bytes();

    /**
     * <code>string server_from_id = 4;</code>
     */
    String getServerFromId();
    /**
     * <code>string server_from_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerFromIdBytes();

    /**
     * <code>string server_to_id = 5;</code>
     */
    String getServerToId();
    /**
     * <code>string server_to_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getServerToIdBytes();

    /**
     * <code>string tip = 6;</code>
     */
    String getTip();
    /**
     * <code>string tip = 6;</code>
     */
    com.google.protobuf.ByteString
        getTipBytes();

    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    java.util.List<String>
        getPassedServersIdList();
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    int getPassedServersIdCount();
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    String getPassedServersId(int index);
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    com.google.protobuf.ByteString
        getPassedServersIdBytes(int index);

    /**
     * <code>int64 timestamp = 8;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      type_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      content2_ = "";
      serverFromId_ = "";
      serverToId_ = "";
      tip_ = "";
      passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              content_ = input.readBytes();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content2_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              serverFromId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              serverToId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              tip_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                passedServersId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              passedServersId_.add(s);
              break;
            }
            case 64: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          passedServersId_ = passedServersId_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SSMessage.internal_static_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SSMessage.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Type type = 1;</code>
     */
    public Type getType() {
      @SuppressWarnings("deprecation")
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int CONTENT2_FIELD_NUMBER = 3;
    private volatile Object content2_;
    /**
     * <code>string content2 = 3;</code>
     */
    public String getContent2() {
      Object ref = content2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content2_ = s;
        return s;
      }
    }
    /**
     * <code>string content2 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContent2Bytes() {
      Object ref = content2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_FROM_ID_FIELD_NUMBER = 4;
    private volatile Object serverFromId_;
    /**
     * <code>string server_from_id = 4;</code>
     */
    public String getServerFromId() {
      Object ref = serverFromId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverFromId_ = s;
        return s;
      }
    }
    /**
     * <code>string server_from_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerFromIdBytes() {
      Object ref = serverFromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverFromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_TO_ID_FIELD_NUMBER = 5;
    private volatile Object serverToId_;
    /**
     * <code>string server_to_id = 5;</code>
     */
    public String getServerToId() {
      Object ref = serverToId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverToId_ = s;
        return s;
      }
    }
    /**
     * <code>string server_to_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServerToIdBytes() {
      Object ref = serverToId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverToId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIP_FIELD_NUMBER = 6;
    private volatile Object tip_;
    /**
     * <code>string tip = 6;</code>
     */
    public String getTip() {
      Object ref = tip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tip_ = s;
        return s;
      }
    }
    /**
     * <code>string tip = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTipBytes() {
      Object ref = tip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSED_SERVERS_ID_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList passedServersId_;
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPassedServersIdList() {
      return passedServersId_;
    }
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public int getPassedServersIdCount() {
      return passedServersId_.size();
    }
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public String getPassedServersId(int index) {
      return passedServersId_.get(index);
    }
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPassedServersIdBytes(int index) {
      return passedServersId_.getByteString(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 8;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Type.UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
      if (!getContent2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content2_);
      }
      if (!getServerFromIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serverFromId_);
      }
      if (!getServerToIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serverToId_);
      }
      if (!getTipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tip_);
      }
      for (int i = 0; i < passedServersId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, passedServersId_.getRaw(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(8, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Type.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      if (!getContent2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content2_);
      }
      if (!getServerFromIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serverFromId_);
      }
      if (!getServerToIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serverToId_);
      }
      if (!getTipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tip_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < passedServersId_.size(); i++) {
          dataSize += computeStringSizeNoTag(passedServersId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPassedServersIdList().size();
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Request)) {
        return super.equals(obj);
      }
      Request other = (Request) obj;

      if (type_ != other.type_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getContent2()
          .equals(other.getContent2())) return false;
      if (!getServerFromId()
          .equals(other.getServerFromId())) return false;
      if (!getServerToId()
          .equals(other.getServerToId())) return false;
      if (!getTip()
          .equals(other.getTip())) return false;
      if (!getPassedServersIdList()
          .equals(other.getPassedServersIdList())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CONTENT2_FIELD_NUMBER;
      hash = (53 * hash) + getContent2().hashCode();
      hash = (37 * hash) + SERVER_FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerFromId().hashCode();
      hash = (37 * hash) + SERVER_TO_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerToId().hashCode();
      hash = (37 * hash) + TIP_FIELD_NUMBER;
      hash = (53 * hash) + getTip().hashCode();
      if (getPassedServersIdCount() > 0) {
        hash = (37 * hash) + PASSED_SERVERS_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPassedServersIdList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SSMessage.internal_static_Request_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SSMessage.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      // Construct using SSMessage.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        content2_ = "";

        serverFromId_ = "";

        serverToId_ = "";

        tip_ = "";

        passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SSMessage.internal_static_Request_descriptor;
      }

      @Override
      public Request getDefaultInstanceForType() {
        return Request.getDefaultInstance();
      }

      @Override
      public Request build() {
        Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Request buildPartial() {
        Request result = new Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.content_ = content_;
        result.content2_ = content2_;
        result.serverFromId_ = serverFromId_;
        result.serverToId_ = serverToId_;
        result.tip_ = tip_;
        if (((bitField0_ & 0x00000040) != 0)) {
          passedServersId_ = passedServersId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.passedServersId_ = passedServersId_;
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Request) {
          return mergeFrom((Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Request other) {
        if (other == Request.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.getContent2().isEmpty()) {
          content2_ = other.content2_;
          onChanged();
        }
        if (!other.getServerFromId().isEmpty()) {
          serverFromId_ = other.serverFromId_;
          onChanged();
        }
        if (!other.getServerToId().isEmpty()) {
          serverToId_ = other.serverToId_;
          onChanged();
        }
        if (!other.getTip().isEmpty()) {
          tip_ = other.tip_;
          onChanged();
        }
        if (!other.passedServersId_.isEmpty()) {
          if (passedServersId_.isEmpty()) {
            passedServersId_ = other.passedServersId_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePassedServersIdIsMutable();
            passedServersId_.addAll(other.passedServersId_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Type getType() {
        @SuppressWarnings("deprecation")
        Type result = Type.valueOf(type_);
        return result == null ? Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private Object content2_ = "";
      /**
       * <code>string content2 = 3;</code>
       */
      public String getContent2() {
        Object ref = content2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContent2Bytes() {
        Object ref = content2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public Builder setContent2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public Builder clearContent2() {
        
        content2_ = getDefaultInstance().getContent2();
        onChanged();
        return this;
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public Builder setContent2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content2_ = value;
        onChanged();
        return this;
      }

      private Object serverFromId_ = "";
      /**
       * <code>string server_from_id = 4;</code>
       */
      public String getServerFromId() {
        Object ref = serverFromId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverFromId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerFromIdBytes() {
        Object ref = serverFromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverFromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public Builder setServerFromId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverFromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public Builder clearServerFromId() {
        
        serverFromId_ = getDefaultInstance().getServerFromId();
        onChanged();
        return this;
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public Builder setServerFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverFromId_ = value;
        onChanged();
        return this;
      }

      private Object serverToId_ = "";
      /**
       * <code>string server_to_id = 5;</code>
       */
      public String getServerToId() {
        Object ref = serverToId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverToId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServerToIdBytes() {
        Object ref = serverToId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverToId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public Builder setServerToId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverToId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public Builder clearServerToId() {
        
        serverToId_ = getDefaultInstance().getServerToId();
        onChanged();
        return this;
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public Builder setServerToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverToId_ = value;
        onChanged();
        return this;
      }

      private Object tip_ = "";
      /**
       * <code>string tip = 6;</code>
       */
      public String getTip() {
        Object ref = tip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tip = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTipBytes() {
        Object ref = tip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tip = 6;</code>
       */
      public Builder setTip(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tip = 6;</code>
       */
      public Builder clearTip() {
        
        tip_ = getDefaultInstance().getTip();
        onChanged();
        return this;
      }
      /**
       * <code>string tip = 6;</code>
       */
      public Builder setTipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tip_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePassedServersIdIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          passedServersId_ = new com.google.protobuf.LazyStringArrayList(passedServersId_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPassedServersIdList() {
        return passedServersId_.getUnmodifiableView();
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public int getPassedServersIdCount() {
        return passedServersId_.size();
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public String getPassedServersId(int index) {
        return passedServersId_.get(index);
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPassedServersIdBytes(int index) {
        return passedServersId_.getByteString(index);
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder setPassedServersId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePassedServersIdIsMutable();
        passedServersId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder addPassedServersId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePassedServersIdIsMutable();
        passedServersId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder addAllPassedServersId(
          Iterable<String> values) {
        ensurePassedServersIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, passedServersId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder clearPassedServersId() {
        passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder addPassedServersIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePassedServersIdIsMutable();
        passedServersId_.add(value);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @Override
    public Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.Type type = 1;</code>
     */
    Type getType();

    /**
     * <code>bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>string content2 = 3;</code>
     */
    String getContent2();
    /**
     * <code>string content2 = 3;</code>
     */
    com.google.protobuf.ByteString
        getContent2Bytes();

    /**
     * <code>string server_from_id = 4;</code>
     */
    String getServerFromId();
    /**
     * <code>string server_from_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerFromIdBytes();

    /**
     * <code>string server_to_id = 5;</code>
     */
    String getServerToId();
    /**
     * <code>string server_to_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getServerToIdBytes();

    /**
     * <code>string tip = 6;</code>
     */
    String getTip();
    /**
     * <code>string tip = 6;</code>
     */
    com.google.protobuf.ByteString
        getTipBytes();

    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    java.util.List<String>
        getPassedServersIdList();
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    int getPassedServersIdCount();
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    String getPassedServersId(int index);
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    com.google.protobuf.ByteString
        getPassedServersIdBytes(int index);

    /**
     * <code>int64 timestamp = 8;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      type_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      content2_ = "";
      serverFromId_ = "";
      serverToId_ = "";
      tip_ = "";
      passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              content_ = input.readBytes();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content2_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              serverFromId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              serverToId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              tip_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                passedServersId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              passedServersId_.add(s);
              break;
            }
            case 64: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          passedServersId_ = passedServersId_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SSMessage.internal_static_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SSMessage.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Type type = 1;</code>
     */
    public Type getType() {
      @SuppressWarnings("deprecation")
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int CONTENT2_FIELD_NUMBER = 3;
    private volatile Object content2_;
    /**
     * <code>string content2 = 3;</code>
     */
    public String getContent2() {
      Object ref = content2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content2_ = s;
        return s;
      }
    }
    /**
     * <code>string content2 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContent2Bytes() {
      Object ref = content2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_FROM_ID_FIELD_NUMBER = 4;
    private volatile Object serverFromId_;
    /**
     * <code>string server_from_id = 4;</code>
     */
    public String getServerFromId() {
      Object ref = serverFromId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverFromId_ = s;
        return s;
      }
    }
    /**
     * <code>string server_from_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerFromIdBytes() {
      Object ref = serverFromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverFromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_TO_ID_FIELD_NUMBER = 5;
    private volatile Object serverToId_;
    /**
     * <code>string server_to_id = 5;</code>
     */
    public String getServerToId() {
      Object ref = serverToId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverToId_ = s;
        return s;
      }
    }
    /**
     * <code>string server_to_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServerToIdBytes() {
      Object ref = serverToId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverToId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIP_FIELD_NUMBER = 6;
    private volatile Object tip_;
    /**
     * <code>string tip = 6;</code>
     */
    public String getTip() {
      Object ref = tip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tip_ = s;
        return s;
      }
    }
    /**
     * <code>string tip = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTipBytes() {
      Object ref = tip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSED_SERVERS_ID_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList passedServersId_;
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPassedServersIdList() {
      return passedServersId_;
    }
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public int getPassedServersIdCount() {
      return passedServersId_.size();
    }
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public String getPassedServersId(int index) {
      return passedServersId_.get(index);
    }
    /**
     * <code>repeated string passed_servers_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPassedServersIdBytes(int index) {
      return passedServersId_.getByteString(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 8;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Type.UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
      if (!getContent2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content2_);
      }
      if (!getServerFromIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serverFromId_);
      }
      if (!getServerToIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serverToId_);
      }
      if (!getTipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tip_);
      }
      for (int i = 0; i < passedServersId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, passedServersId_.getRaw(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(8, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Type.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      if (!getContent2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content2_);
      }
      if (!getServerFromIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serverFromId_);
      }
      if (!getServerToIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serverToId_);
      }
      if (!getTipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tip_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < passedServersId_.size(); i++) {
          dataSize += computeStringSizeNoTag(passedServersId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPassedServersIdList().size();
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Response)) {
        return super.equals(obj);
      }
      Response other = (Response) obj;

      if (type_ != other.type_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getContent2()
          .equals(other.getContent2())) return false;
      if (!getServerFromId()
          .equals(other.getServerFromId())) return false;
      if (!getServerToId()
          .equals(other.getServerToId())) return false;
      if (!getTip()
          .equals(other.getTip())) return false;
      if (!getPassedServersIdList()
          .equals(other.getPassedServersIdList())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CONTENT2_FIELD_NUMBER;
      hash = (53 * hash) + getContent2().hashCode();
      hash = (37 * hash) + SERVER_FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerFromId().hashCode();
      hash = (37 * hash) + SERVER_TO_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerToId().hashCode();
      hash = (37 * hash) + TIP_FIELD_NUMBER;
      hash = (53 * hash) + getTip().hashCode();
      if (getPassedServersIdCount() > 0) {
        hash = (37 * hash) + PASSED_SERVERS_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPassedServersIdList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SSMessage.internal_static_Response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SSMessage.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.class, Builder.class);
      }

      // Construct using SSMessage.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        content2_ = "";

        serverFromId_ = "";

        serverToId_ = "";

        tip_ = "";

        passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SSMessage.internal_static_Response_descriptor;
      }

      @Override
      public Response getDefaultInstanceForType() {
        return Response.getDefaultInstance();
      }

      @Override
      public Response build() {
        Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Response buildPartial() {
        Response result = new Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.content_ = content_;
        result.content2_ = content2_;
        result.serverFromId_ = serverFromId_;
        result.serverToId_ = serverToId_;
        result.tip_ = tip_;
        if (((bitField0_ & 0x00000040) != 0)) {
          passedServersId_ = passedServersId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.passedServersId_ = passedServersId_;
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Response) {
          return mergeFrom((Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Response other) {
        if (other == Response.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.getContent2().isEmpty()) {
          content2_ = other.content2_;
          onChanged();
        }
        if (!other.getServerFromId().isEmpty()) {
          serverFromId_ = other.serverFromId_;
          onChanged();
        }
        if (!other.getServerToId().isEmpty()) {
          serverToId_ = other.serverToId_;
          onChanged();
        }
        if (!other.getTip().isEmpty()) {
          tip_ = other.tip_;
          onChanged();
        }
        if (!other.passedServersId_.isEmpty()) {
          if (passedServersId_.isEmpty()) {
            passedServersId_ = other.passedServersId_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePassedServersIdIsMutable();
            passedServersId_.addAll(other.passedServersId_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Type getType() {
        @SuppressWarnings("deprecation")
        Type result = Type.valueOf(type_);
        return result == null ? Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private Object content2_ = "";
      /**
       * <code>string content2 = 3;</code>
       */
      public String getContent2() {
        Object ref = content2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContent2Bytes() {
        Object ref = content2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public Builder setContent2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public Builder clearContent2() {
        
        content2_ = getDefaultInstance().getContent2();
        onChanged();
        return this;
      }
      /**
       * <code>string content2 = 3;</code>
       */
      public Builder setContent2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content2_ = value;
        onChanged();
        return this;
      }

      private Object serverFromId_ = "";
      /**
       * <code>string server_from_id = 4;</code>
       */
      public String getServerFromId() {
        Object ref = serverFromId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverFromId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerFromIdBytes() {
        Object ref = serverFromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverFromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public Builder setServerFromId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverFromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public Builder clearServerFromId() {
        
        serverFromId_ = getDefaultInstance().getServerFromId();
        onChanged();
        return this;
      }
      /**
       * <code>string server_from_id = 4;</code>
       */
      public Builder setServerFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverFromId_ = value;
        onChanged();
        return this;
      }

      private Object serverToId_ = "";
      /**
       * <code>string server_to_id = 5;</code>
       */
      public String getServerToId() {
        Object ref = serverToId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverToId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServerToIdBytes() {
        Object ref = serverToId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverToId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public Builder setServerToId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverToId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public Builder clearServerToId() {
        
        serverToId_ = getDefaultInstance().getServerToId();
        onChanged();
        return this;
      }
      /**
       * <code>string server_to_id = 5;</code>
       */
      public Builder setServerToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverToId_ = value;
        onChanged();
        return this;
      }

      private Object tip_ = "";
      /**
       * <code>string tip = 6;</code>
       */
      public String getTip() {
        Object ref = tip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tip = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTipBytes() {
        Object ref = tip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tip = 6;</code>
       */
      public Builder setTip(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tip = 6;</code>
       */
      public Builder clearTip() {
        
        tip_ = getDefaultInstance().getTip();
        onChanged();
        return this;
      }
      /**
       * <code>string tip = 6;</code>
       */
      public Builder setTipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tip_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePassedServersIdIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          passedServersId_ = new com.google.protobuf.LazyStringArrayList(passedServersId_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPassedServersIdList() {
        return passedServersId_.getUnmodifiableView();
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public int getPassedServersIdCount() {
        return passedServersId_.size();
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public String getPassedServersId(int index) {
        return passedServersId_.get(index);
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPassedServersIdBytes(int index) {
        return passedServersId_.getByteString(index);
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder setPassedServersId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePassedServersIdIsMutable();
        passedServersId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder addPassedServersId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePassedServersIdIsMutable();
        passedServersId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder addAllPassedServersId(
          Iterable<String> values) {
        ensurePassedServersIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, passedServersId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder clearPassedServersId() {
        passedServersId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string passed_servers_id = 7;</code>
       */
      public Builder addPassedServersIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePassedServersIdIsMutable();
        passedServersId_.add(value);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Response();
    }

    public static Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @Override
    public Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017SSMessage.proto\"\252\001\n\007Request\022\023\n\004type\030\001 " +
      "\001(\0162\005.Type\022\017\n\007content\030\002 \001(\014\022\020\n\010content2\030" +
      "\003 \001(\t\022\026\n\016server_from_id\030\004 \001(\t\022\024\n\014server_" +
      "to_id\030\005 \001(\t\022\013\n\003tip\030\006 \001(\t\022\031\n\021passed_serve" +
      "rs_id\030\007 \003(\t\022\021\n\ttimestamp\030\010 \001(\003\"\253\001\n\010Respo" +
      "nse\022\023\n\004type\030\001 \001(\0162\005.Type\022\017\n\007content\030\002 \001(" +
      "\014\022\020\n\010content2\030\003 \001(\t\022\026\n\016server_from_id\030\004 " +
      "\001(\t\022\024\n\014server_to_id\030\005 \001(\t\022\013\n\003tip\030\006 \001(\t\022\031" +
      "\n\021passed_servers_id\030\007 \003(\t\022\021\n\ttimestamp\030\010" +
      " \001(\003*-\n\004Type\022\013\n\007UNKNOWN\020\000\022\030\n\024CLIENT_STAT" +
      "E_CHANGED\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new String[] { "Type", "Content", "Content2", "ServerFromId", "ServerToId", "Tip", "PassedServersId", "Timestamp", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "Type", "Content", "Content2", "ServerFromId", "ServerToId", "Tip", "PassedServersId", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
